// Auto-generated by `supabase gen types typescript` against project
// fjwoaszceqchmntgxlab. Convenience aliases at the bottom of this file are
// hand-maintained — keep them in sync when regenerating.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      audit_log: {
        Row: {
          action: string
          created_at: string
          entity_id: string | null
          entity_type: string
          id: string
          payload: Json
          user_id: string | null
          workspace_id: string | null
        }
        Insert: {
          action: string
          created_at?: string
          entity_id?: string | null
          entity_type: string
          id?: string
          payload?: Json
          user_id?: string | null
          workspace_id?: string | null
        }
        Update: {
          action?: string
          created_at?: string
          entity_id?: string | null
          entity_type?: string
          id?: string
          payload?: Json
          user_id?: string | null
          workspace_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "audit_log_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "audit_log_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      comments: {
        Row: {
          body: string
          created_at: string
          entity_id: string
          entity_type: Database["public"]["Enums"]["comment_entity"]
          id: string
          parent_id: string | null
          user_id: string
        }
        Insert: {
          body: string
          created_at?: string
          entity_id: string
          entity_type: Database["public"]["Enums"]["comment_entity"]
          id?: string
          parent_id?: string | null
          user_id: string
        }
        Update: {
          body?: string
          created_at?: string
          entity_id?: string
          entity_type?: Database["public"]["Enums"]["comment_entity"]
          id?: string
          parent_id?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "comments_parent_id_fkey"
            columns: ["parent_id"]
            isOneToOne: false
            referencedRelation: "comments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "comments_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      enzyme_candidates: {
        Row: {
          created_at: string
          ec_number: string | null
          embedding: string | null
          id: string
          metadata: Json
          mutations: Json
          name: string
          organism: string | null
          parent_id: string | null
          parent_sequence: string | null
          pdb_id: string | null
          project_id: string
          sequence: string
          source: Database["public"]["Enums"]["candidate_source"]
          source_id: string | null
        }
        Insert: {
          created_at?: string
          ec_number?: string | null
          embedding?: string | null
          id?: string
          metadata?: Json
          mutations?: Json
          name: string
          organism?: string | null
          parent_id?: string | null
          parent_sequence?: string | null
          pdb_id?: string | null
          project_id: string
          sequence: string
          source: Database["public"]["Enums"]["candidate_source"]
          source_id?: string | null
        }
        Update: {
          created_at?: string
          ec_number?: string | null
          embedding?: string | null
          id?: string
          metadata?: Json
          mutations?: Json
          name?: string
          organism?: string | null
          parent_id?: string | null
          parent_sequence?: string | null
          pdb_id?: string | null
          project_id?: string
          sequence?: string
          source?: Database["public"]["Enums"]["candidate_source"]
          source_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "enzyme_candidates_parent_id_fkey"
            columns: ["parent_id"]
            isOneToOne: false
            referencedRelation: "enzyme_candidates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "enzyme_candidates_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      experiments: {
        Row: {
          attachments: Json
          candidate_id: string
          created_at: string
          id: string
          measured_activity: number | null
          measured_stability: number | null
          measured_yield: number | null
          notes: string | null
          performed_at: string
          performed_by: string
          prediction_id: string | null
        }
        Insert: {
          attachments?: Json
          candidate_id: string
          created_at?: string
          id?: string
          measured_activity?: number | null
          measured_stability?: number | null
          measured_yield?: number | null
          notes?: string | null
          performed_at?: string
          performed_by: string
          prediction_id?: string | null
        }
        Update: {
          attachments?: Json
          candidate_id?: string
          created_at?: string
          id?: string
          measured_activity?: number | null
          measured_stability?: number | null
          measured_yield?: number | null
          notes?: string | null
          performed_at?: string
          performed_by?: string
          prediction_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "experiments_candidate_id_fkey"
            columns: ["candidate_id"]
            isOneToOne: false
            referencedRelation: "enzyme_candidates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "experiments_performed_by_fkey"
            columns: ["performed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "experiments_prediction_id_fkey"
            columns: ["prediction_id"]
            isOneToOne: false
            referencedRelation: "predictions"
            referencedColumns: ["id"]
          },
        ]
      }
      model_calibration: {
        Row: {
          calibration_params: Json
          id: string
          mae_activity: number | null
          mae_stability: number | null
          mae_yield: number | null
          model_version: string
          n_observations: number
          updated_at: string
        }
        Insert: {
          calibration_params?: Json
          id?: string
          mae_activity?: number | null
          mae_stability?: number | null
          mae_yield?: number | null
          model_version: string
          n_observations: number
          updated_at?: string
        }
        Update: {
          calibration_params?: Json
          id?: string
          mae_activity?: number | null
          mae_stability?: number | null
          mae_yield?: number | null
          model_version?: string
          n_observations?: number
          updated_at?: string
        }
        Relationships: []
      }
      pathway_designs: {
        Row: {
          bottlenecks: Json
          created_at: string
          graph: Json
          id: string
          name: string
          predicted_flux: number | null
          project_id: string
        }
        Insert: {
          bottlenecks?: Json
          created_at?: string
          graph: Json
          id?: string
          name: string
          predicted_flux?: number | null
          project_id: string
        }
        Update: {
          bottlenecks?: Json
          created_at?: string
          graph?: Json
          id?: string
          name?: string
          predicted_flux?: number | null
          project_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "pathway_designs_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      predictions: {
        Row: {
          activity_score: number
          candidate_id: string
          confidence_lower: number
          confidence_upper: number
          created_at: string
          expression_score: number
          features: Json
          id: string
          model_version: string
          predicted_yield: number
          stability_score: number
        }
        Insert: {
          activity_score: number
          candidate_id: string
          confidence_lower: number
          confidence_upper: number
          created_at?: string
          expression_score: number
          features?: Json
          id?: string
          model_version: string
          predicted_yield: number
          stability_score: number
        }
        Update: {
          activity_score?: number
          candidate_id?: string
          confidence_lower?: number
          confidence_upper?: number
          created_at?: string
          expression_score?: number
          features?: Json
          id?: string
          model_version?: string
          predicted_yield?: number
          stability_score?: number
        }
        Relationships: [
          {
            foreignKeyName: "predictions_candidate_id_fkey"
            columns: ["candidate_id"]
            isOneToOne: false
            referencedRelation: "enzyme_candidates"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          created_at: string
          email: string
          full_name: string | null
          id: string
          role: Database["public"]["Enums"]["user_role"]
        }
        Insert: {
          created_at?: string
          email: string
          full_name?: string | null
          id: string
          role?: Database["public"]["Enums"]["user_role"]
        }
        Update: {
          created_at?: string
          email?: string
          full_name?: string | null
          id?: string
          role?: Database["public"]["Enums"]["user_role"]
        }
        Relationships: []
      }
      projects: {
        Row: {
          conditions: Json
          created_at: string
          created_by: string
          id: string
          name: string
          product: string | null
          substrate: string | null
          target_reaction: string | null
          workspace_id: string
        }
        Insert: {
          conditions?: Json
          created_at?: string
          created_by: string
          id?: string
          name: string
          product?: string | null
          substrate?: string | null
          target_reaction?: string | null
          workspace_id: string
        }
        Update: {
          conditions?: Json
          created_at?: string
          created_by?: string
          id?: string
          name?: string
          product?: string | null
          substrate?: string | null
          target_reaction?: string | null
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "projects_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "projects_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      retrieval_cache: {
        Row: {
          cache_key: string
          created_at: string
          expires_at: string
          id: string
          payload: Json
          source: string
        }
        Insert: {
          cache_key: string
          created_at?: string
          expires_at: string
          id?: string
          payload: Json
          source: string
        }
        Update: {
          cache_key?: string
          created_at?: string
          expires_at?: string
          id?: string
          payload?: Json
          source?: string
        }
        Relationships: []
      }
      workspace_members: {
        Row: {
          created_at: string
          role: Database["public"]["Enums"]["workspace_role"]
          user_id: string
          workspace_id: string
        }
        Insert: {
          created_at?: string
          role?: Database["public"]["Enums"]["workspace_role"]
          user_id: string
          workspace_id: string
        }
        Update: {
          created_at?: string
          role?: Database["public"]["Enums"]["workspace_role"]
          user_id?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "workspace_members_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "workspace_members_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      workspaces: {
        Row: {
          created_at: string
          id: string
          name: string
          owner_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          name: string
          owner_id: string
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
          owner_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "workspaces_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      can_edit_workspace: { Args: { ws_id: string }; Returns: boolean }
      candidate_workspace: { Args: { c_id: string }; Returns: string }
      is_workspace_member: { Args: { ws_id: string }; Returns: boolean }
      project_workspace: { Args: { p_id: string }; Returns: string }
      workspace_role_of: {
        Args: { ws_id: string }
        Returns: Database["public"]["Enums"]["workspace_role"]
      }
    }
    Enums: {
      candidate_source: "db" | "generated"
      comment_entity: "candidate" | "experiment" | "pathway"
      user_role: "researcher" | "admin"
      workspace_role: "owner" | "editor" | "viewer"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      candidate_source: ["db", "generated"],
      comment_entity: ["candidate", "experiment", "pathway"],
      user_role: ["researcher", "admin"],
      workspace_role: ["owner", "editor", "viewer"],
    },
  },
} as const

// ─── EnzymeForge convenience aliases ────────────────────────────────────────

export type UserRole = Database["public"]["Enums"]["user_role"];
export type WorkspaceRole = Database["public"]["Enums"]["workspace_role"];
export type CandidateSource = Database["public"]["Enums"]["candidate_source"];
export type CommentEntity = Database["public"]["Enums"]["comment_entity"];

export type Profile = Database["public"]["Tables"]["profiles"]["Row"];
export type Workspace = Database["public"]["Tables"]["workspaces"]["Row"];
export type WorkspaceMember = Database["public"]["Tables"]["workspace_members"]["Row"];
export type Project = Database["public"]["Tables"]["projects"]["Row"];
export type EnzymeCandidate = Database["public"]["Tables"]["enzyme_candidates"]["Row"];
export type Prediction = Database["public"]["Tables"]["predictions"]["Row"];
export type PathwayDesign = Database["public"]["Tables"]["pathway_designs"]["Row"];
export type Experiment = Database["public"]["Tables"]["experiments"]["Row"];
export type ModelCalibration = Database["public"]["Tables"]["model_calibration"]["Row"];
export type Comment = Database["public"]["Tables"]["comments"]["Row"];
export type AuditLog = Database["public"]["Tables"]["audit_log"]["Row"];

/**
 * Mutation entry stored in `enzyme_candidates.mutations` (a `jsonb` array).
 * The DB column is typed as `Json`; this is the agreed-upon shape across the app.
 */
export interface Mutation {
  position: number;
  from: string;
  to: string;
  score?: number;
}
